### PR TITLE
Define default subcommand.

### PR DESCRIPTION
**Pull request by laxmorek**
It allows to omit the `lint` subcommand in a call and makes linting more convenient.

**Before:** 

`tuist swiftlint lint`

**After:**

`tuist swiftlint`

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]
What do you think of renaming the base command to `lint`, so you have to do `tuist lint` instead of `tuist swiftlint`? 🤔

**Comment by laxmorek** [comment]
I don't have a strong opinion about it. Do you think it would be better to rename it? 🤔

**Comment by danyf90** [comment]
> I don't have a strong opinion about it. Do you think it would be better to rename it? 🤔

no strong opinion, too. But I would probably rename it.
Using just lint is:
- easier (shorter)
- more flexible (e.g. tomorrow we might add some linting which is not part of swiftlint, or switch to another tool)

**Comment by laxmorek** [comment]
One more thing. 

When we change the main command to `lint` then the full call will change to:

```
tuist lint lint
```

Of course with default subcommand it will be possible to call it as `tuist lint`. 

We have to consider other subcommands too. After the change it will be:

```
tuist lint version
tuist lint version-swiftlint
```

For me it still looks good. 

Anyway how does it look like for you? Does it change your mind? @danyf90

**Comment by danyf90** [comment]
The main one could be tuist lint swiftlint.
The version command prints the version of the plugin or of the swiftlint?

**Comment by laxmorek** [comment]
> The main one could be tuist lint swiftlint.

I like it 

> The version command prints the version of the plugin or of the swiftlint?

Both. We have the one for plugin version and the one for swiftlint version.

**Review by danyf90 — APPROVED** [review]

**Pull request merged**
